### ISSUE TITLE
how to run this codes?

### ISSUE THREAD

**Issue by LeeYongHyeok** [themattrosen/Planeverb#5]
Hi @themattrosen, I am so impressed with your pjt.
I want to test my code using my own virtual room environment, signals, etc.
But I don't know how to run this code with Unity.
Can you write a step-by-step usage?

**Comment by LeeYongHyeok** [comment]
+ When I run your code, do I need to prepare an Azure account and budget?

**Comment by themattrosen** [comment]
Hi LeeYongHyeok,
You don't need an Azure account to run Planeverb. Planeverb runs on a single thread on your computer. 
I'll add a Unity integration guide and add it to the README. Thanks for opening an issue!

-Matt

**Comment by themattrosen** [comment]
I've added the integration instructions to the ReadMe! Let me know if you run into any issues.
