### ISSUE TITLE
Analyzer LPF cutoff frequency equation

### ISSUE THREAD

**Issue by algebrait** [themattrosen/Planeverb#6]
Hi @themattrosen, thanks for your great job!
Would you show some detail of how to get Analyzer LPF cutoff frequency equation?
https://github.com/themattrosen/Planeverb/blob/69239a552191219b1e70ef5dc5eb85bc24818117/ProjectPlaneverb/src/DSP/Analyzer.cpp#L228

**Comment by themattrosen** [comment]
Hi algebrait, I used [this blog post](https://codeandsound.wordpress.com/2014/08/21/absorption-of-sound-by-air-and-its-implementation-as-a-filter-part-1-theory/) and the graphs included to make a heuristic plot of cut-off frequencies to distance, and graphed it with a best-fit curve. That best-fit curve is the resulting equation, roughly translating distance into a lowpass filter cutoff, at 0m above sea level and at 20C. I use a 6dB-per-octave rolloff LPF (I believe I used a Butterworth filter for it).
